# Generated by Django 5.1.2 on 2024-12-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='admin_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='date',
        ),
        migrations.RemoveField(
            model_name='school',
            name='image',
        ),
        migrations.RemoveField(
            model_name='school',
            name='time',
        ),
    ]
